name: Todos

on:
  push:
    branches:
     - main

jobs:
  todos:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: todo-actions
      uses: dtinth/todo-actions@master
